import type { Metadata } from 'next';
import { Pacifico, Montserrat } from 'next/font/google';
import './globals.css';

const montserrat = Montserrat({
  subsets: ['cyrillic'],
  variable: '--font-main',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
});

const pacifico = Pacifico({
  subsets: ['cyrillic'],
  variable: '--font-write',
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${pacifico.variable}`}>
      <body>
        <div>{children}</div>
      </body>
    </html>
  );
}
